import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import InstallAppContextProvider from "@/context/InstallAppContextProvider";
import { ToastContainer } from "react-toastify";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({
  weight: "400",
  subsets: ["latin"],
});
export const metadata = {
  title: "Play-Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <header className="bg-base-100 shadow-sm">
          <Navbar></Navbar>
        </header>
        <main>
          <InstallAppContextProvider>{children}</InstallAppContextProvider>
        </main>
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
